'n': 10
p: 0.15
t: 10000
batch_size: 16
lr: 0.01
gamma: 0.99
sync_rate: 10
replay_size: 1000
warm_start_size: 1000
eps_last_frame: 1000
eps_start: 1.0
eps_end: 0.01
episode_length: 200
warm_start_steps: 1000
c_hidden: 32
c_out: 1
num_layers: 2
layer_name: GCN
m: 1
_instantiator: lightning.pytorch.cli.instantiate_module
