# lightning.pytorch==2.3.3
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  n: 10
  p: 0.15
  t: 10000
  batch_size: 16
  lr: 0.01
  gamma: 0.99
  sync_rate: 10
  replay_size: 1000
  warm_start_size: 1000
  eps_last_frame: 1000
  eps_start: 1.0
  eps_end: 0.01
  episode_length: 200
  warm_start_steps: 1000
  c_in: null
  c_hidden: 32
  c_out: 1
  num_layers: 2
  layer_name: GCN
  dp_rate: null
  m: 1
data: null
optimizer: null
lr_scheduler: null
ckpt_path: null
